### ISSUE TITLE
使用zookeeper-client运行失败

### ISSUE THREAD

**Issue by chclock** [RabbitTeam/zookeeper-client#1]
失败信息： Unhandled Exception: System.AggregateException: One or more errors occurred. (Operation cannot be retried because of retry timeout (60000 milli seconds)) ---> System.TimeoutException: Operation cannot be retried because of retry timeout (60000 milli seconds)
测试代码：
static void Main(string[] args)
        {
            IZookeeperClient client = new ZookeeperClient(new ZookeeperClientOptions("127.0.0.1:2181")
            {
                BasePath = "/", //default value
                ConnectionTimeout = TimeSpan.FromSeconds(10), //default value
                SessionTimeout = TimeSpan.FromSeconds(20), //default value
                OperatingTimeout = TimeSpan.FromSeconds(60), //default value
                ReadOnly = false, //default value
                SessionId = 0, //default value
                SessionPasswd = null, //default value
                EnableEphemeralNodeRestore = true //default value
            });
            var result = client.ExistsAsync("/").Result;
            Console.WriteLine($"Exist: {result}");
        }
我改用原生的ZooKeeperNetEx测试，也报"org.apache.zookeeper.KeeperException+ConnectionLossException”错误。

**Comment by majian159** [comment]
确保zookeeper server正常，这与组件无关，所以我会关闭这个issue。

**Comment by chclock** [comment]
我检查了下，是zookeeper server配置错误，改正好都正常运行了。
